// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wep_programlama_proje.Data;

#nullable disable

namespace wep_programlama_proje.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241221033453_dbOlustur1")]
    partial class dbOlustur1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("wep_programlama_proje.Data.Calisan", b =>
                {
                    b.Property<int>("CalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalisanAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalisanUzmanlik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CalisanId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("wep_programlama_proje.Data.Hizmet", b =>
                {
                    b.Property<int>("HizmetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HizmetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ucret")
                        .HasColumnType("INTEGER");

                    b.HasKey("HizmetId");

                    b.ToTable("Hizmetler");
                });

            modelBuilder.Entity("wep_programlama_proje.Data.Musteri", b =>
                {
                    b.Property<int>("MusteiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MusteriAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MusteiId");

                    b.ToTable("Musteriler");
                });
#pragma warning restore 612, 618
        }
    }
}
