// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_programlama_proje.Models;

#nullable disable

namespace web_programlama_proje.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241226003543_sqlite_migration_708")]
    partial class sqlite_migration_708
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("web_programlama_proje.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AdminId");

                    b.ToTable("Adminler");
                });

            modelBuilder.Entity("web_programlama_proje.Models.Calisan", b =>
                {
                    b.Property<int>("CalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalisanAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalisanEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CalisanId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("web_programlama_proje.Models.CalisanHizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HizmetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("HizmetId");

                    b.ToTable("calisanHizmet");
                });

            modelBuilder.Entity("web_programlama_proje.Models.Hizmet", b =>
                {
                    b.Property<int>("HizmetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HimzetUcret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HizmetAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HizmetId");

                    b.ToTable("Hizmetler");
                });

            modelBuilder.Entity("web_programlama_proje.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreOnay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("web_programlama_proje.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HizmetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RandevuTarih")
                        .HasColumnType("TEXT");

                    b.HasKey("RandevuId");

                    b.HasIndex("CalisanId");

                    b.HasIndex("HizmetId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("web_programlama_proje.Models.CalisanHizmet", b =>
                {
                    b.HasOne("web_programlama_proje.Models.Calisan", "Calisan")
                        .WithMany("Hizmetler")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_programlama_proje.Models.Hizmet", "Hizmet")
                        .WithMany("Calisanlar")
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Hizmet");
                });

            modelBuilder.Entity("web_programlama_proje.Models.Randevu", b =>
                {
                    b.HasOne("web_programlama_proje.Models.Calisan", "Calisan")
                        .WithMany("Randevular")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_programlama_proje.Models.Hizmet", "Hizmet")
                        .WithMany()
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_programlama_proje.Models.Kullanici", "Kullanici")
                        .WithMany("KullaniciRandevular")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Hizmet");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("web_programlama_proje.Models.Calisan", b =>
                {
                    b.Navigation("Hizmetler");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("web_programlama_proje.Models.Hizmet", b =>
                {
                    b.Navigation("Calisanlar");
                });

            modelBuilder.Entity("web_programlama_proje.Models.Kullanici", b =>
                {
                    b.Navigation("KullaniciRandevular");
                });
#pragma warning restore 612, 618
        }
    }
}
